import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';

const TARGET_DIR = join(process.cwd(), 'packages/protocol/src');
const TARGET_FILE = join(TARGET_DIR, 'build-info.ts');

let buildId = '';
try {
  buildId = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  buildId = `build-${Date.now()}`;
}

const content = `// Auto-generated by generate-build-info.ts
export const BUILD_ID = '${buildId}';
`;

mkdirSync(TARGET_DIR, { recursive: true });
writeFileSync(TARGET_FILE, content, 'utf8');
console.log(`Generated build info with BUILD_ID: ${buildId}`);
